apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Dev-
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: Dev-
spec:
  project: private-project
  source:
    repoURL: https://github.com/ankan-devops/k8s-mysql-replicaset.git
    targetRevision:
    path: overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true