apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ankan-devops/k8s-mysql-replicaset.git
  password: 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
  username: ankan-devops