apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: applicationset
spec:
  project: private-project
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ankan-devops/k8s-mysql-replicaset.git
    targetRevision: argo-create
    path: overlays/kustomization*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m