kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv1
# spec:
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: mysql-sc
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   local:
#     path: /data
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - minikube-m03

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv2
# spec:
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: mysql-sc
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   local:
#     path: /data
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - minikube-m02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.121
    path: /home/ankan/k8s-mysql/1
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.121
    path: /home/ankan/k8s-mysql/2
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv3
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.121
    path: /home/ankan/k8s-mysql/3
  mountOptions:
    - nfsvers=4.2