apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql-replicaset

spec:
  selector:
    app: mysql-replica
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-router
  namespace: mysql-replicaset
  labels:
    app: mysql-router
spec:
  selector:
    app: mysql-router
  ports:
  - name: mysql-rw
    port: 6446
  - name: mysql-ro
    port: 6447