apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script
  namespace: mysql-replicaset

data:
  mysql-script.sh: |
    #!/bin/sh
    sleep 60;
    if [ ! -f /var/lib/mysql/admin-user.sh ] ; then
    if [ $HOSTNAME == 'mysql-replica-0' ]; then
      mysqlsh -h ${HOSTNAME}.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.createCluster("testCluster")';
    fi;
    touch /var/lib/mysql/admin-user.sh;
    else
    curl -f -s -I mysql-router:6446;
    if [ $? == 8 ]; then
      mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().removeInstance("root@'${HOSTNAME}'.mysql-svc", { interactive: false, force: true })';
    else
      mysqlsh -h ${HOSTNAME}.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.rebootClusterFromCompleteOutage("testCluster")';
    fi;
    fi;
    while :
    do
      curl -f -s -I mysql-router:6446;
      if  [ $? != 8 ]; then
        sleep 3;
      else
        mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().rescan({ interactive:false, addInstances:"auto", removeInstances:"auto" })';
        sleep $(( 105*$(echo $HOSTNAME | tr -dc '[0-9]') ));
        break;
      fi;
    done;
    mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().addInstance("root@'${HOSTNAME}'.mysql-svc", { recoveryMethod: "clone", waitRecovery: 0 })';
    wait; rm -f /var/lib/mysql/admin-user.sh;