apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script
  namespace: mysql-replicaset

data:
  mysql-script.sh: |
    #!/bin/sh
    sleep 30;
    if [ ! -f /var/lib/mysql/admin-user.sh ] ; then
    if [ $HOSTNAME == 'mysql-replica-0' ]; then
      mysqlsh -h ${HOSTNAME}.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.createCluster("testCluster")';
    fi;
    touch /var/lib/mysql/admin-user.sh;
    elif [ ! -f /var/lib/mysql/temp.sh ]; then
    curl -f -s -I mysql-router:6446;
    if [ $? == 8 ]; then
      mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().removeInstance("root@'${HOSTNAME}'.mysql-svc", { interactive: false, force: true })';
    else
      mysqlsh -h ${HOSTNAME}.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.rebootClusterFromCompleteOutage("testCluster")';
      sleep 5;
      mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().rescan({ interactive:false, addInstances:"auto", removeInstances:"auto" })';
    fi;
    else
    rm -f /var/lib/mysql/temp.sh;
    mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().rescan({ interactive:false, addInstances:"auto", removeInstances:"auto" })';
    exit;
    fi;

    while :
    do
      curl -f -s -I mysql-router:6446;
      if  [ $? != 8 ]; then
        sleep 3;
      else
        sleep $(( 10+85*$(echo $HOSTNAME | tr -dc '[0-9]') ));
        break;
      fi;
    done;
    mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().addInstance("root@'${HOSTNAME}'.mysql-svc", { recoveryMethod: "clone", waitRecovery: 0 })' && touch /var/lib/mysql/temp.sh;