apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script
  namespace: mysql-replicaset

data:
  mysql-script.sh: |
    #!/bin/sh
    sleep 60;
    if [ ! -f /var/lib/mysql/admin-user.sh ] ; then
    if [ $HOSTNAME == 'mysql-replica-0' ]; then
      mysqlsh -h ${HOSTNAME}.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.createCluster("testCluster")';
    else
      sleep 20;
    fi;
    else
    sleep 15;
    if [ $HOSTNAME == 'mysql-replica-0' ]; then
      mysqlsh -h ${HOSTNAME}.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.rebootClusterFromCompleteOutage()';
    fi;
    mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().removeInstance("root@'${HOSTNAME}'.mysql-svc", { interactive: false, force: true })';
    rm -f /var/lib/mysql/admin-user.sh;
    fi;
    mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().rescan({ interactive:false, addInstances:"auto", removeInstances:"auto" })'
    sleep 90;
    mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().addInstance("root@'${HOSTNAME}'.mysql-svc", { recoveryMethod: "clone", waitRecovery: 3 })';
    touch /var/lib/mysql/admin-user.sh;