apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script
  namespace: mysql-replicaset

data:
  mysql-script.sh: |
    #!/bin/sh
    sleep 120;
    if [ ! -f /var/lib/mysql/admin-user.sh ] ; then
    if [ $HOSTNAME == 'mysql-replica-0' ]; then
      mysqlsh -h ${HOSTNAME}.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.rebootClusterFromCompleteOutage()';
      mysqlsh -h ${HOSTNAME}.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.createCluster("testCluster")';
    fi;
    sleep 45;
    mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().addInstance("root@'${HOSTNAME}'.mysql-svc", { recoveryMethod: "clone", waitRecovery: false })';
    else
      sleep 45;
      mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().removeInstance("root@'${HOSTNAME}'.mysql-svc", { interactive: false })';
      rm -f /var/lib/mysql/admin-user.sh;
      exit 1;
    fi;
  # mysqlsh -h mysql-router -P 6446 -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().rescan({ interactive:false, addInstances:"auto", removeInstances:"auto"  })'
    touch /var/lib/mysql/admin-user.sh;