apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script
  namespace: mysql-replicaset

data:
  mysql-script.sh: |
    #!/bin/sh
    sleep 200;
    if [ ! -f /var/lib/mysql/admin-user.sh ]; then
    if [ $HOSTNAME == 'mysql-replica-0' ]; then
      mysqlsh -h mysql-replica-0.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.createCluster("testCluster")';
    else
      mysqlsh -h mysql-replica-0.mysql-svc -u root -p${MYSQL_ROOT_PASSWORD} -e 'dba.getCluster().addInstance("root@'${HOSTNAME}'.mysql-svc", {recoveryMethod: "clone"})';
    fi;
    touch /var/lib/mysql/admin-user.sh; fi;