apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router
  namespace: mysql-replicaset
  labels:
    app: mysql-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-router
  template:
    metadata:
      labels:
        app: mysql-router
    spec:
      containers:
      - name: mysql-router
        image: mysql/mysql-router:latest
        env:
        - name: MYSQL_HOST
          value: mysql-replica-0.mysql-svc
        - name: MYSQL_PORT
          value: '3306'
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - name: mysql-rw
          containerPort: 6446
        - name: mysql-ro
          containerPort: 6447